/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelrelojes.panelrelojes.UI;

/**
 *
 * @author cving
 */
public class PanelPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelPrincipal.class.getName());
    private vRelojDigital reloj1;
    private vRelojDigital reloj2;
    private vRelojDigital reloj3;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        reloj1 = new vRelojDigital();
        reloj1.setVisible(true);
        reloj2 = new vRelojDigital();
        reloj2.setVisible(true);
        reloj3 = new vRelojDigital();
        reloj3.setVisible(true);
       
        initComponents();
        getContentPane().add(reloj1);
        getContentPane().add(reloj2);
        getContentPane().add(reloj3);
        Thread treloj = new Thread(reloj1);
        Thread treloj2 = new Thread(reloj2);
        Thread treloj3 = new Thread(reloj3);
        treloj.start();
        treloj2.start();
        treloj3.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Relojes");
        setPreferredSize(new java.awt.Dimension(1000, 200));
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
