/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelrelojes.panelrelojes.UI;

import panelrelojes.panelrelojes.logica.RelojDigital;

/**
 *
 * @author cving
 */
public class vRelojDigital extends javax.swing.JPanel implements Runnable{
    private RelojDigital relojd;
    private boolean stop;
    /**
     * Creates new form vRelojDigital
     */
    public vRelojDigital() {
        stop=false;
        relojd=new RelojDigital();
        initComponents();
        upReloj();
    }
    public vRelojDigital(int hh,int mm, int ss) {
        stop=false;
        relojd=new RelojDigital(hh,mm,ss);
        initComponents();
        upReloj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTfHh = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtFMm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFSs = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jLabel1.setText("HH:MM:SS");

        jButton1.setText("Stop");
        jButton1.setToolTipText("Detener");
        jButton1.setName("btnStop"); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTfHh.setName("tfHoras"); // NOI18N

        jButton2.setText("Edit");
        jButton2.setName("btnEdit"); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Play");
        jButton3.setName("btnPlay"); // NOI18N
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel2.setText(":");

        jtFMm.setName("tfMinutos"); // NOI18N

        jLabel3.setText(":");

        jTFSs.setName("tfSegundos"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTfHh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtFMm, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfHh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtFMm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTFSs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      stop=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
stop=false;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(!jTfHh.getText().isEmpty()){
           relojd.setHour(Integer.parseInt(jTfHh.getText()));
           jTfHh.setText("");
           upReloj();
       
      }
      if(!jtFMm.getText().isEmpty()){
          relojd.setMin(Integer.parseInt(jtFMm.getText()));
          jtFMm.setText("");
          upReloj();
 
      }
      if(!jTFSs.getText().isEmpty()){
          relojd.setSecond(Integer.parseInt(jTFSs.getText()));
           jTFSs.setText("");
           upReloj();
 
      }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFSs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTfHh;
    private javax.swing.JTextField jtFMm;
    // End of variables declaration//GEN-END:variables

    private  void upReloj(){
         jLabel1.setText(relojd.toString());
    }
    @Override
    public void run() {
        while (true) {
            
           try {
            Thread.sleep(1000);
            if(stop) continue;
            relojd.addSecond();
            upReloj();
        } catch (InterruptedException ex) {
            System.getLogger(vRelojDigital.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            
        }
        
    }
}
